name: analyze

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: koji-1009/setup-flutter@dd35dcb6aeccda37e5042e1a03aed95e46611a3d # v1.2.1
      - run: flutter pub get
      - run: dart analyze

  format:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: koji-1009/setup-flutter@dd35dcb6aeccda37e5042e1a03aed95e46611a3d # v1.2.1
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .
      - run: dart run dapper --set-exit-if-changed .

  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: koji-1009/setup-flutter@dd35dcb6aeccda37e5042e1a03aed95e46611a3d # v1.2.1
      - run: flutter pub get
      - run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
