name: analyze

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: koji-1009/setup-flutter@da1d7a630a98e2b43650b81da73deb5ac838980f # v1.0.4
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart analyze

  format:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: koji-1009/setup-flutter@da1d7a630a98e2b43650b81da73deb5ac838980f # v1.0.4
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .
      - run: dart run dapper --set-exit-if-changed .

  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: koji-1009/setup-flutter@da1d7a630a98e2b43650b81da73deb5ac838980f # v1.0.4
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
