name: analyze

on:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: koji-1009/setup-flutter@e869444283cdc5705870adddd145d42cd1cfd627 # v1.1.2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart analyze

  format:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: koji-1009/setup-flutter@e869444283cdc5705870adddd145d42cd1cfd627 # v1.1.2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: dart format --set-exit-if-changed .
      - run: dart run dapper --set-exit-if-changed .

  test:
    runs-on: ubuntu-slim
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: koji-1009/setup-flutter@e869444283cdc5705870adddd145d42cd1cfd627 # v1.1.2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@1af58845a975a7985b0beb0cbe6fbbb71a41dbad # v5.5.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
